# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64581140e7faf03573b290d01eb1b66cf6a2f4f37eb4ca2afa8be724ee0c7fcda9c8fd575ed04371f1809c31a37c5184349017f1bca54059653d260f3f791999
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 6aee6639494b7ca6224862bda3b583280d77391045e320478c27ecfa5303f87c49e02c6bfb5a1ef9693c080ac88a58b2e59d264b36bd5709662876ee70e87eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
